/* tslint:disable */
/* eslint-disable */
/**
 * Eve API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BlueprintDto
 */
export interface BlueprintDto {
    /**
     * 
     * @type {number}
     * @memberof BlueprintDto
     */
    'activityId': number | null;
    /**
     * 
     * @type {string}
     * @memberof BlueprintDto
     */
    'blueprintName': string | null;
    /**
     * 
     * @type {number}
     * @memberof BlueprintDto
     */
    'blueprintId': number;
    /**
     * 
     * @type {string}
     * @memberof BlueprintDto
     */
    'productName': string | null;
    /**
     * 
     * @type {number}
     * @memberof BlueprintDto
     */
    'productId': number;
    /**
     * 
     * @type {number}
     * @memberof BlueprintDto
     */
    'categoryId': number;
    /**
     * 
     * @type {number}
     * @memberof BlueprintDto
     */
    'groupId': number;
}

