/* tslint:disable */
/* eslint-disable */
/**
 * Eve API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IndustryActivityProduct
 */
export interface IndustryActivityProduct {
    /**
     * 
     * @type {number}
     * @memberof IndustryActivityProduct
     */
    'typeId'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof IndustryActivityProduct
     */
    'activityId'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof IndustryActivityProduct
     */
    'productTypeId'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof IndustryActivityProduct
     */
    'quantity'?: number | null;
}

