/* tslint:disable */
/* eslint-disable */
/**
 * Eve API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InvTypeShortDto
 */
export interface InvTypeShortDto {
    /**
     * 
     * @type {number}
     * @memberof InvTypeShortDto
     */
    'typeId': number;
    /**
     * 
     * @type {string}
     * @memberof InvTypeShortDto
     */
    'typeName': string | null;
}

