/* tslint:disable */
/* eslint-disable */
/**
 * Eve API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InvGroupDto
 */
export interface InvGroupDto {
    /**
     * 
     * @type {number}
     * @memberof InvGroupDto
     */
    'groupId': number;
    /**
     * 
     * @type {string}
     * @memberof InvGroupDto
     */
    'groupName'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof InvGroupDto
     */
    'categoryId'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof InvGroupDto
     */
    'iconId'?: number | null;
}

