/* tslint:disable */
/* eslint-disable */
/**
 * Eve API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MarketGroupNodeDto
 */
export interface MarketGroupNodeDto {
    /**
     * 
     * @type {number}
     * @memberof MarketGroupNodeDto
     */
    'marketGroupId'?: number;
    /**
     * 
     * @type {string}
     * @memberof MarketGroupNodeDto
     */
    'marketGroupName'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MarketGroupNodeDto
     */
    'iconId'?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof MarketGroupNodeDto
     */
    'hasTypes'?: boolean | null;
    /**
     * 
     * @type {Array<MarketGroupNodeDto>}
     * @memberof MarketGroupNodeDto
     */
    'children'?: Array<MarketGroupNodeDto> | null;
}

