/* tslint:disable */
/* eslint-disable */
/**
 * Eve API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface InvTypeDto
 */
export interface InvTypeDto {
    /**
     * 
     * @type {number}
     * @memberof InvTypeDto
     */
    'typeId': number;
    /**
     * 
     * @type {string}
     * @memberof InvTypeDto
     */
    'typeName': string | null;
    /**
     * 
     * @type {string}
     * @memberof InvTypeDto
     */
    'description'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof InvTypeDto
     */
    'iconId'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof InvTypeDto
     */
    'graphicId'?: number | null;
}
/**
 * 
 * @export
 * @interface InvTypeShortDto
 */
export interface InvTypeShortDto {
    /**
     * 
     * @type {number}
     * @memberof InvTypeShortDto
     */
    'typeId': number;
    /**
     * 
     * @type {string}
     * @memberof InvTypeShortDto
     */
    'typeName': string | null;
}

/**
 * InvTypesApi - axios parameter creator
 * @export
 */
export const InvTypesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} [searchString] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiInvTypesGet: async (searchString?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/InvTypes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (searchString !== undefined) {
                localVarQueryParameter['searchString'] = searchString;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiInvTypesIdGet: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiInvTypesIdGet', 'id', id)
            const localVarPath = `/api/InvTypes/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InvTypesApi - functional programming interface
 * @export
 */
export const InvTypesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = InvTypesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} [searchString] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiInvTypesGet(searchString?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<InvTypeShortDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiInvTypesGet(searchString, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InvTypesApi.apiInvTypesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiInvTypesIdGet(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InvTypeDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiInvTypesIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InvTypesApi.apiInvTypesIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * InvTypesApi - factory interface
 * @export
 */
export const InvTypesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = InvTypesApiFp(configuration)
    return {
        /**
         * 
         * @param {string} [searchString] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiInvTypesGet(searchString?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<InvTypeShortDto>> {
            return localVarFp.apiInvTypesGet(searchString, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiInvTypesIdGet(id: number, options?: RawAxiosRequestConfig): AxiosPromise<InvTypeDto> {
            return localVarFp.apiInvTypesIdGet(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * InvTypesApi - object-oriented interface
 * @export
 * @class InvTypesApi
 * @extends {BaseAPI}
 */
export class InvTypesApi extends BaseAPI {
    /**
     * 
     * @param {string} [searchString] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvTypesApi
     */
    public apiInvTypesGet(searchString?: string, options?: RawAxiosRequestConfig) {
        return InvTypesApiFp(this.configuration).apiInvTypesGet(searchString, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvTypesApi
     */
    public apiInvTypesIdGet(id: number, options?: RawAxiosRequestConfig) {
        return InvTypesApiFp(this.configuration).apiInvTypesIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }
}



