/* tslint:disable */
/* eslint-disable */
/**
 * Eve API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { IndustryActivityMaterial } from '../models';
/**
 * IndustryActivityMaterialsApi - axios parameter creator
 * @export
 */
export const IndustryActivityMaterialsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} [typeId] 
         * @param {number} [activityId] 
         * @param {number} [materialTypeId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiIndustryActivityMaterialsGet: async (typeId?: number, activityId?: number, materialTypeId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/industry-activity-materials`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (typeId !== undefined) {
                localVarQueryParameter['typeId'] = typeId;
            }

            if (activityId !== undefined) {
                localVarQueryParameter['activityId'] = activityId;
            }

            if (materialTypeId !== undefined) {
                localVarQueryParameter['materialTypeId'] = materialTypeId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} typeId 
         * @param {number} activityId 
         * @param {number} materialTypeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiIndustryActivityMaterialsTypeIdActivityIdMaterialTypeIdGet: async (typeId: number, activityId: number, materialTypeId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'typeId' is not null or undefined
            assertParamExists('apiIndustryActivityMaterialsTypeIdActivityIdMaterialTypeIdGet', 'typeId', typeId)
            // verify required parameter 'activityId' is not null or undefined
            assertParamExists('apiIndustryActivityMaterialsTypeIdActivityIdMaterialTypeIdGet', 'activityId', activityId)
            // verify required parameter 'materialTypeId' is not null or undefined
            assertParamExists('apiIndustryActivityMaterialsTypeIdActivityIdMaterialTypeIdGet', 'materialTypeId', materialTypeId)
            const localVarPath = `/api/industry-activity-materials/{typeId}/{activityId}/{materialTypeId}`
                .replace(`{${"typeId"}}`, encodeURIComponent(String(typeId)))
                .replace(`{${"activityId"}}`, encodeURIComponent(String(activityId)))
                .replace(`{${"materialTypeId"}}`, encodeURIComponent(String(materialTypeId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * IndustryActivityMaterialsApi - functional programming interface
 * @export
 */
export const IndustryActivityMaterialsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = IndustryActivityMaterialsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} [typeId] 
         * @param {number} [activityId] 
         * @param {number} [materialTypeId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiIndustryActivityMaterialsGet(typeId?: number, activityId?: number, materialTypeId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<IndustryActivityMaterial>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiIndustryActivityMaterialsGet(typeId, activityId, materialTypeId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IndustryActivityMaterialsApi.apiIndustryActivityMaterialsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} typeId 
         * @param {number} activityId 
         * @param {number} materialTypeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiIndustryActivityMaterialsTypeIdActivityIdMaterialTypeIdGet(typeId: number, activityId: number, materialTypeId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IndustryActivityMaterial>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiIndustryActivityMaterialsTypeIdActivityIdMaterialTypeIdGet(typeId, activityId, materialTypeId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IndustryActivityMaterialsApi.apiIndustryActivityMaterialsTypeIdActivityIdMaterialTypeIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * IndustryActivityMaterialsApi - factory interface
 * @export
 */
export const IndustryActivityMaterialsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = IndustryActivityMaterialsApiFp(configuration)
    return {
        /**
         * 
         * @param {number} [typeId] 
         * @param {number} [activityId] 
         * @param {number} [materialTypeId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiIndustryActivityMaterialsGet(typeId?: number, activityId?: number, materialTypeId?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<IndustryActivityMaterial>> {
            return localVarFp.apiIndustryActivityMaterialsGet(typeId, activityId, materialTypeId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} typeId 
         * @param {number} activityId 
         * @param {number} materialTypeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiIndustryActivityMaterialsTypeIdActivityIdMaterialTypeIdGet(typeId: number, activityId: number, materialTypeId: number, options?: RawAxiosRequestConfig): AxiosPromise<IndustryActivityMaterial> {
            return localVarFp.apiIndustryActivityMaterialsTypeIdActivityIdMaterialTypeIdGet(typeId, activityId, materialTypeId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * IndustryActivityMaterialsApi - object-oriented interface
 * @export
 * @class IndustryActivityMaterialsApi
 * @extends {BaseAPI}
 */
export class IndustryActivityMaterialsApi extends BaseAPI {
    /**
     * 
     * @param {number} [typeId] 
     * @param {number} [activityId] 
     * @param {number} [materialTypeId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IndustryActivityMaterialsApi
     */
    public apiIndustryActivityMaterialsGet(typeId?: number, activityId?: number, materialTypeId?: number, options?: RawAxiosRequestConfig) {
        return IndustryActivityMaterialsApiFp(this.configuration).apiIndustryActivityMaterialsGet(typeId, activityId, materialTypeId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} typeId 
     * @param {number} activityId 
     * @param {number} materialTypeId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IndustryActivityMaterialsApi
     */
    public apiIndustryActivityMaterialsTypeIdActivityIdMaterialTypeIdGet(typeId: number, activityId: number, materialTypeId: number, options?: RawAxiosRequestConfig) {
        return IndustryActivityMaterialsApiFp(this.configuration).apiIndustryActivityMaterialsTypeIdActivityIdMaterialTypeIdGet(typeId, activityId, materialTypeId, options).then((request) => request(this.axios, this.basePath));
    }
}

